name: Deploy to Railway
on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
      - name: Build with Maven
        run: mvn package --batch-mode --file pom.xml
      - name: Install Railway CLI
        run: curl -sSL https://get.railway.app | sh
      - name: Deploy to Railway
        env:
          RAILWAY_TOKEN: ${{ secrets.RAILWAY_TOKEN }}
        run: railway deploy --platform=nodejs --env railway.properties --command "java -jar target/*.jar"
